apiVersion: v1
kind: ConfigMap
metadata:
  name: notas-config
data:
  APP_TITLE: "API de notas"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notas-deployment

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: notas

  template:
    metadata:
      labels:
        app: notas

    spec:
      containers:
        - name: notas
          image: devops-act1:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 2
            periodSeconds: 2

          env:
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: notas-config
                  key: APP_TITLE

            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: notas-data
              mountPath: /data

      volumes:
        - name: notas-data
          hostPath:
            path: /data/notas
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: notas-service

spec:
  selector:
    app: notas

  ports:
    - port: 5000
      targetPort: 5000

  type: NodePort